version: 1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: inRL/NLbu3JvKGK/p09ooPLQ/eY8tFLxgYbdC5VoSdh7Ecdf0+tUlPaaO5uAzjRp
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/