version: 1.1.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: inRL/NLbu3JvKGK/p09ooPLQ/eY8tFLxgYbdC5VoSdh7Ecdf0+tUlPaaO5uAzjRp
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/